//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileDB.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FileDB.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        public static string SearchBrowseButton {
            get {
                return ResourceManager.GetString("SearchBrowseButton", resourceCulture);
            }
        }
        
        public static string SearchNewFilesButton {
            get {
                return ResourceManager.GetString("SearchNewFilesButton", resourceCulture);
            }
        }
        
        public static string SearchAllFromCurrentDirectoryButton {
            get {
                return ResourceManager.GetString("SearchAllFromCurrentDirectoryButton", resourceCulture);
            }
        }
        
        public static string SearchFromCurrentFileButton {
            get {
                return ResourceManager.GetString("SearchFromCurrentFileButton", resourceCulture);
            }
        }
        
        public static string SearchForFilesWithinSelectedDirectoryToolTip {
            get {
                return ResourceManager.GetString("SearchForFilesWithinSelectedDirectoryToolTip", resourceCulture);
            }
        }
        
        public static string SearchAllFilesWithinCurrentFileDirectoryToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesWithinCurrentFileDirectoryToolTip", resourceCulture);
            }
        }
        
        public static string SearchNewFilesButtonToolTip {
            get {
                return ResourceManager.GetString("SearchNewFilesButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchRandomFilesToolTip {
            get {
                return ResourceManager.GetString("SearchRandomFilesToolTip", resourceCulture);
            }
        }
        
        public static string SearchAllFilesFromSearch1ThatAlsoBelongToSearch2ToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesFromSearch1ThatAlsoBelongToSearch2ToolTip", resourceCulture);
            }
        }
        
        public static string SearchAllFilesFromSearch1And2ToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesFromSearch1And2ToolTip", resourceCulture);
            }
        }
        
        public static string SearchAllFilesThatAreInEitherOfTheSearchesButNotInTheirIntersectionToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesThatAreInEitherOfTheSearchesButNotInTheirIntersectionToolTip", resourceCulture);
            }
        }
        
        public static string SearchIntersectionButton {
            get {
                return ResourceManager.GetString("SearchIntersectionButton", resourceCulture);
            }
        }
        
        public static string SearchUnionButton {
            get {
                return ResourceManager.GetString("SearchUnionButton", resourceCulture);
            }
        }
        
        public static string SearchDifferenceButton {
            get {
                return ResourceManager.GetString("SearchDifferenceButton", resourceCulture);
            }
        }
        
        public static string SearchCopyButton {
            get {
                return ResourceManager.GetString("SearchCopyButton", resourceCulture);
            }
        }
        
        public static string SearchOpenButton {
            get {
                return ResourceManager.GetString("SearchOpenButton", resourceCulture);
            }
        }
        
        public static string SearchBasicLabel {
            get {
                return ResourceManager.GetString("SearchBasicLabel", resourceCulture);
            }
        }
        
        public static string SearchRandomFilesLabel {
            get {
                return ResourceManager.GetString("SearchRandomFilesLabel", resourceCulture);
            }
        }
        
        public static string SearchCombineLabel {
            get {
                return ResourceManager.GetString("SearchCombineLabel", resourceCulture);
            }
        }
        
        public static string SearchCombineSearch1Label {
            get {
                return ResourceManager.GetString("SearchCombineSearch1Label", resourceCulture);
            }
        }
        
        public static string SearchCombineSearch2Label {
            get {
                return ResourceManager.GetString("SearchCombineSearch2Label", resourceCulture);
            }
        }
        
        public static string SearchCombineResultLabel {
            get {
                return ResourceManager.GetString("SearchCombineResultLabel", resourceCulture);
            }
        }
        
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        public static string AboutGettingStartedTitle {
            get {
                return ResourceManager.GetString("AboutGettingStartedTitle", resourceCulture);
            }
        }
        
        public static string AboutNotesTitle {
            get {
                return ResourceManager.GetString("AboutNotesTitle", resourceCulture);
            }
        }
        
        public static string AboutCommandLineArgumentsTitle {
            get {
                return ResourceManager.GetString("AboutCommandLineArgumentsTitle", resourceCulture);
            }
        }
        
        public static string AboutChangelogTitle {
            get {
                return ResourceManager.GetString("AboutChangelogTitle", resourceCulture);
            }
        }
        
        public static string AboutLicenseLabel {
            get {
                return ResourceManager.GetString("AboutLicenseLabel", resourceCulture);
            }
        }
        
        public static string AboutNuGetPackageLicensesTitle {
            get {
                return ResourceManager.GetString("AboutNuGetPackageLicensesTitle", resourceCulture);
            }
        }
        
        public static string AboutGettingStarted1 {
            get {
                return ResourceManager.GetString("AboutGettingStarted1", resourceCulture);
            }
        }
        
        public static string AboutGettingStarted2 {
            get {
                return ResourceManager.GetString("AboutGettingStarted2", resourceCulture);
            }
        }
        
        public static string AboutGettingStarted4 {
            get {
                return ResourceManager.GetString("AboutGettingStarted4", resourceCulture);
            }
        }
        
        public static string AboutGettingStarted5 {
            get {
                return ResourceManager.GetString("AboutGettingStarted5", resourceCulture);
            }
        }
        
        public static string AboutGettingStarted6 {
            get {
                return ResourceManager.GetString("AboutGettingStarted6", resourceCulture);
            }
        }
        
        public static string AboutNotes1 {
            get {
                return ResourceManager.GetString("AboutNotes1", resourceCulture);
            }
        }
        
        public static string AboutNotes2 {
            get {
                return ResourceManager.GetString("AboutNotes2", resourceCulture);
            }
        }
        
        public static string AboutNotes3 {
            get {
                return ResourceManager.GetString("AboutNotes3", resourceCulture);
            }
        }
        
        public static string AboutCommandLineArgPathText {
            get {
                return ResourceManager.GetString("AboutCommandLineArgPathText", resourceCulture);
            }
        }
        
        public static string AboutDownloadsReleases {
            get {
                return ResourceManager.GetString("AboutDownloadsReleases", resourceCulture);
            }
        }
        
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        public static string AddLocationNameLabel {
            get {
                return ResourceManager.GetString("AddLocationNameLabel", resourceCulture);
            }
        }
        
        public static string AddLocationDescriptionLabel {
            get {
                return ResourceManager.GetString("AddLocationDescriptionLabel", resourceCulture);
            }
        }
        
        public static string AddLocationPositionLabel {
            get {
                return ResourceManager.GetString("AddLocationPositionLabel", resourceCulture);
            }
        }
        
        public static string AddLocationPositionToolTip {
            get {
                return ResourceManager.GetString("AddLocationPositionToolTip", resourceCulture);
            }
        }
        
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        public static string AddPersonFirstnameLabel {
            get {
                return ResourceManager.GetString("AddPersonFirstnameLabel", resourceCulture);
            }
        }
        
        public static string AddPersonLastnameLabel {
            get {
                return ResourceManager.GetString("AddPersonLastnameLabel", resourceCulture);
            }
        }
        
        public static string AddPersonSexLabel {
            get {
                return ResourceManager.GetString("AddPersonSexLabel", resourceCulture);
            }
        }
        
        public static string AddPersonDescriptionLabel {
            get {
                return ResourceManager.GetString("AddPersonDescriptionLabel", resourceCulture);
            }
        }
        
        public static string AddPersonDateOfBirthLabel {
            get {
                return ResourceManager.GetString("AddPersonDateOfBirthLabel", resourceCulture);
            }
        }
        
        public static string AddPersonDeceasedLabel {
            get {
                return ResourceManager.GetString("AddPersonDeceasedLabel", resourceCulture);
            }
        }
        
        public static string AddPersonProfilePictureFileIdLabel {
            get {
                return ResourceManager.GetString("AddPersonProfilePictureFileIdLabel", resourceCulture);
            }
        }
        
        public static string AddPersonSetCurrentFileLabel {
            get {
                return ResourceManager.GetString("AddPersonSetCurrentFileLabel", resourceCulture);
            }
        }
        
        public static string AddPersonSetCurrentFileToolTip {
            get {
                return ResourceManager.GetString("AddPersonSetCurrentFileToolTip", resourceCulture);
            }
        }
        
        public static string AddTagNameLabel {
            get {
                return ResourceManager.GetString("AddTagNameLabel", resourceCulture);
            }
        }
        
        public static string BirthdaysTitle {
            get {
                return ResourceManager.GetString("BirthdaysTitle", resourceCulture);
            }
        }
        
        public static string RipTitle {
            get {
                return ResourceManager.GetString("RipTitle", resourceCulture);
            }
        }
        
        public static string BrowseDirectoriesSelectYourDirectoryLabel {
            get {
                return ResourceManager.GetString("BrowseDirectoriesSelectYourDirectoryLabel", resourceCulture);
            }
        }
        
        public static string BrowseDirectoriesSelectButton {
            get {
                return ResourceManager.GetString("BrowseDirectoriesSelectButton", resourceCulture);
            }
        }
        
        public static string BrowseDirectoriesSelectToolTip {
            get {
                return ResourceManager.GetString("BrowseDirectoriesSelectToolTip", resourceCulture);
            }
        }
        
        public static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        public static string ExportHeaderLabel {
            get {
                return ResourceManager.GetString("ExportHeaderLabel", resourceCulture);
            }
        }
        
        public static string ExportHeaderToolTip {
            get {
                return ResourceManager.GetString("ExportHeaderToolTip", resourceCulture);
            }
        }
        
        public static string ExportDestinationLabel {
            get {
                return ResourceManager.GetString("ExportDestinationLabel", resourceCulture);
            }
        }
        
        public static string ExportBrowseButton {
            get {
                return ResourceManager.GetString("ExportBrowseButton", resourceCulture);
            }
        }
        
        public static string ExportSearchResultFilesLabel {
            get {
                return ResourceManager.GetString("ExportSearchResultFilesLabel", resourceCulture);
            }
        }
        
        public static string ExportM3UPlaylistLabel {
            get {
                return ResourceManager.GetString("ExportM3UPlaylistLabel", resourceCulture);
            }
        }
        
        public static string ExportHTMLWithMetaDataAndSearchResultFilesLabel {
            get {
                return ResourceManager.GetString("ExportHTMLWithMetaDataAndSearchResultFilesLabel", resourceCulture);
            }
        }
        
        public static string ExportSearchResultFilesWithMetaDataLabel {
            get {
                return ResourceManager.GetString("ExportSearchResultFilesWithMetaDataLabel", resourceCulture);
            }
        }
        
        public static string ExportSearchResultMetaDataJSONLabel {
            get {
                return ResourceManager.GetString("ExportSearchResultMetaDataJSONLabel", resourceCulture);
            }
        }
        
        public static string ExportExportButton {
            get {
                return ResourceManager.GetString("ExportExportButton", resourceCulture);
            }
        }
        
        public static string TagsTitle {
            get {
                return ResourceManager.GetString("TagsTitle", resourceCulture);
            }
        }
        
        public static string TagsAddButton {
            get {
                return ResourceManager.GetString("TagsAddButton", resourceCulture);
            }
        }
        
        public static string TagEditButton {
            get {
                return ResourceManager.GetString("TagEditButton", resourceCulture);
            }
        }
        
        public static string TagsDeleteButton {
            get {
                return ResourceManager.GetString("TagsDeleteButton", resourceCulture);
            }
        }
        
        public static string LocationsTitle {
            get {
                return ResourceManager.GetString("LocationsTitle", resourceCulture);
            }
        }
        
        public static string LocationsAddButton {
            get {
                return ResourceManager.GetString("LocationsAddButton", resourceCulture);
            }
        }
        
        public static string LocationsEditButton {
            get {
                return ResourceManager.GetString("LocationsEditButton", resourceCulture);
            }
        }
        
        public static string LocationsDeleteButton {
            get {
                return ResourceManager.GetString("LocationsDeleteButton", resourceCulture);
            }
        }
        
        public static string LocationsShowOnMapButton {
            get {
                return ResourceManager.GetString("LocationsShowOnMapButton", resourceCulture);
            }
        }
        
        public static string PersonsTitle {
            get {
                return ResourceManager.GetString("PersonsTitle", resourceCulture);
            }
        }
        
        public static string PersonsAddButton {
            get {
                return ResourceManager.GetString("PersonsAddButton", resourceCulture);
            }
        }
        
        public static string PersonsEditButton {
            get {
                return ResourceManager.GetString("PersonsEditButton", resourceCulture);
            }
        }
        
        public static string PersonsDeleteButton {
            get {
                return ResourceManager.GetString("PersonsDeleteButton", resourceCulture);
            }
        }
        
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        public static string FilesTitle {
            get {
                return ResourceManager.GetString("FilesTitle", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string ToolsTitle {
            get {
                return ResourceManager.GetString("ToolsTitle", resourceCulture);
            }
        }
        
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        public static string ExitToolTip {
            get {
                return ResourceManager.GetString("ExitToolTip", resourceCulture);
            }
        }
        
        public static string NotificationsDismissAllButton {
            get {
                return ResourceManager.GetString("NotificationsDismissAllButton", resourceCulture);
            }
        }
        
        public static string NotificationsNoNotificationsAvailable {
            get {
                return ResourceManager.GetString("NotificationsNoNotificationsAvailable", resourceCulture);
            }
        }
        
        public static string SearchLocateButtonToolTip {
            get {
                return ResourceManager.GetString("SearchLocateButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchOpenButtonToolTip {
            get {
                return ResourceManager.GetString("SearchOpenButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchCopyButtonToolTip {
            get {
                return ResourceManager.GetString("SearchCopyButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchRemoveButtonToolTip {
            get {
                return ResourceManager.GetString("SearchRemoveButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchToggleLargeTextButtonToolTip {
            get {
                return ResourceManager.GetString("SearchToggleLargeTextButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchOpenPresentationWindowButtonToolTip {
            get {
                return ResourceManager.GetString("SearchOpenPresentationWindowButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchMaximizeButtonToolTip {
            get {
                return ResourceManager.GetString("SearchMaximizeButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultHistoryLabel {
            get {
                return ResourceManager.GetString("SearchResultHistoryLabel", resourceCulture);
            }
        }
        
        public static string SearchResultExportButton {
            get {
                return ResourceManager.GetString("SearchResultExportButton", resourceCulture);
            }
        }
        
        public static string SearchResultCopyButtonToolTip {
            get {
                return ResourceManager.GetString("SearchResultCopyButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultCloseButtonToolTip {
            get {
                return ResourceManager.GetString("SearchResultCloseButtonToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultSortByLabel {
            get {
                return ResourceManager.GetString("SearchResultSortByLabel", resourceCulture);
            }
        }
        
        public static string SearchResultGoToPreviousToolTip {
            get {
                return ResourceManager.GetString("SearchResultGoToPreviousToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultGoToNextToolTip {
            get {
                return ResourceManager.GetString("SearchResultGoToNextToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultGoToPreviousDirectoryToolTip {
            get {
                return ResourceManager.GetString("SearchResultGoToPreviousDirectoryToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultGoToNextDirectoryToolTip {
            get {
                return ResourceManager.GetString("SearchResultGoToNextDirectoryToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultGoToFirstToolTip {
            get {
                return ResourceManager.GetString("SearchResultGoToFirstToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultGoToLastToolTip {
            get {
                return ResourceManager.GetString("SearchResultGoToLastToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultToggleSlideshowToolTip {
            get {
                return ResourceManager.GetString("SearchResultToggleSlideshowToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultToggleSlideshowRandomToolTip {
            get {
                return ResourceManager.GetString("SearchResultToggleSlideshowRandomToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultToggleSlideshowRepeatToolTip {
            get {
                return ResourceManager.GetString("SearchResultToggleSlideshowRepeatToolTip", resourceCulture);
            }
        }
        
        public static string SearchResultToggleFileDescriptionSpeekToolTip {
            get {
                return ResourceManager.GetString("SearchResultToggleFileDescriptionSpeekToolTip", resourceCulture);
            }
        }
        
        public static string FileInfoTitle {
            get {
                return ResourceManager.GetString("FileInfoTitle", resourceCulture);
            }
        }
        
        public static string FileInfoPersonsToolTip {
            get {
                return ResourceManager.GetString("FileInfoPersonsToolTip", resourceCulture);
            }
        }
        
        public static string FileInfoLocationsToolTip {
            get {
                return ResourceManager.GetString("FileInfoLocationsToolTip", resourceCulture);
            }
        }
        
        public static string FileInfoTagsToolTip {
            get {
                return ResourceManager.GetString("FileInfoTagsToolTip", resourceCulture);
            }
        }
        
        public static string FileInfoPositionToolTip {
            get {
                return ResourceManager.GetString("FileInfoPositionToolTip", resourceCulture);
            }
        }
        
        public static string FileInfoDescriptionToolTip {
            get {
                return ResourceManager.GetString("FileInfoDescriptionToolTip", resourceCulture);
            }
        }
        
        public static string PresentationWindowTitle {
            get {
                return ResourceManager.GetString("PresentationWindowTitle", resourceCulture);
            }
        }
        
        public static string AddLocationEditTitle {
            get {
                return ResourceManager.GetString("AddLocationEditTitle", resourceCulture);
            }
        }
        
        public static string AddLocationAddTitle {
            get {
                return ResourceManager.GetString("AddLocationAddTitle", resourceCulture);
            }
        }
        
        public static string AddPersonEditTitle {
            get {
                return ResourceManager.GetString("AddPersonEditTitle", resourceCulture);
            }
        }
        
        public static string AddPersonAddTitle {
            get {
                return ResourceManager.GetString("AddPersonAddTitle", resourceCulture);
            }
        }
        
        public static string AddTagEditTitle {
            get {
                return ResourceManager.GetString("AddTagEditTitle", resourceCulture);
            }
        }
        
        public static string AddTagAddTitle {
            get {
                return ResourceManager.GetString("AddTagAddTitle", resourceCulture);
            }
        }
        
        public static string SettingsResetChangesButton {
            get {
                return ResourceManager.GetString("SettingsResetChangesButton", resourceCulture);
            }
        }
        
        public static string SettingsResetChangesButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsResetChangesButtonToolTip", resourceCulture);
            }
        }
        
        public static string SettingsSaveButton {
            get {
                return ResourceManager.GetString("SettingsSaveButton", resourceCulture);
            }
        }
        
        public static string SettingsDefaultButton {
            get {
                return ResourceManager.GetString("SettingsDefaultButton", resourceCulture);
            }
        }
        
        public static string SettingsDefaultButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsDefaultButtonToolTip", resourceCulture);
            }
        }
        
        public static string SettingsGeneralHeading {
            get {
                return ResourceManager.GetString("SettingsGeneralHeading", resourceCulture);
            }
        }
        
        public static string SettingsBrowsingHeading {
            get {
                return ResourceManager.GetString("SettingsBrowsingHeading", resourceCulture);
            }
        }
        
        public static string SettingsImportHeading {
            get {
                return ResourceManager.GetString("SettingsImportHeading", resourceCulture);
            }
        }
        
        public static string SettingsNotificationsHeading {
            get {
                return ResourceManager.GetString("SettingsNotificationsHeading", resourceCulture);
            }
        }
        
        public static string SettingsPerformanceHeading {
            get {
                return ResourceManager.GetString("SettingsPerformanceHeading", resourceCulture);
            }
        }
        
        public static string SettingsWindowModeLabel {
            get {
                return ResourceManager.GetString("SettingsWindowModeLabel", resourceCulture);
            }
        }
        
        public static string SettingsLanguageLabel {
            get {
                return ResourceManager.GetString("SettingsLanguageLabel", resourceCulture);
            }
        }
        
        public static string SettingsReadOnlyModeLabel {
            get {
                return ResourceManager.GetString("SettingsReadOnlyModeLabel", resourceCulture);
            }
        }
        
        public static string SettingsSlideshowDelaySecondsLabel {
            get {
                return ResourceManager.GetString("SettingsSlideshowDelaySecondsLabel", resourceCulture);
            }
        }
        
        public static string SettingsSearchHistorySizeLabel {
            get {
                return ResourceManager.GetString("SettingsSearchHistorySizeLabel", resourceCulture);
            }
        }
        
        public static string SettingsLocationLinkLabel {
            get {
                return ResourceManager.GetString("SettingsLocationLinkLabel", resourceCulture);
            }
        }
        
        public static string SettingsOverlayTextSizeLabel {
            get {
                return ResourceManager.GetString("SettingsOverlayTextSizeLabel", resourceCulture);
            }
        }
        
        public static string SettingsOverlayTextSizeForLargeModeLabel {
            get {
                return ResourceManager.GetString("SettingsOverlayTextSizeForLargeModeLabel", resourceCulture);
            }
        }
        
        public static string SettingsShortItemNameMaxLengthLabel {
            get {
                return ResourceManager.GetString("SettingsShortItemNameMaxLengthLabel", resourceCulture);
            }
        }
        
        public static string SettingsDefaultSortMethodLabel {
            get {
                return ResourceManager.GetString("SettingsDefaultSortMethodLabel", resourceCulture);
            }
        }
        
        public static string SettingsKeepSelectionAfterSortLabel {
            get {
                return ResourceManager.GetString("SettingsKeepSelectionAfterSortLabel", resourceCulture);
            }
        }
        
        public static string SettingsBlacklistedFilePathPatternsLabel {
            get {
                return ResourceManager.GetString("SettingsBlacklistedFilePathPatternsLabel", resourceCulture);
            }
        }
        
        public static string SettingsWhitelistedFilePathPatternsLabel {
            get {
                return ResourceManager.GetString("SettingsWhitelistedFilePathPatternsLabel", resourceCulture);
            }
        }
        
        public static string SettingsLocationMaxDistanceAtImportLabel {
            get {
                return ResourceManager.GetString("SettingsLocationMaxDistanceAtImportLabel", resourceCulture);
            }
        }
        
        public static string SettingsIncludeHiddenDirectoriesLabel {
            get {
                return ResourceManager.GetString("SettingsIncludeHiddenDirectoriesLabel", resourceCulture);
            }
        }
        
        public static string SettingsBirthdayReminderLabel {
            get {
                return ResourceManager.GetString("SettingsBirthdayReminderLabel", resourceCulture);
            }
        }
        
        public static string SettingsBirthdayReminderForDeceasedLabel {
            get {
                return ResourceManager.GetString("SettingsBirthdayReminderForDeceasedLabel", resourceCulture);
            }
        }
        
        public static string SettingsRIPReminderLabel {
            get {
                return ResourceManager.GetString("SettingsRIPReminderLabel", resourceCulture);
            }
        }
        
        public static string SettingsFilesRootDirectoryMissingLabel {
            get {
                return ResourceManager.GetString("SettingsFilesRootDirectoryMissingLabel", resourceCulture);
            }
        }
        
        public static string SettingsBackupReminderLabel {
            get {
                return ResourceManager.GetString("SettingsBackupReminderLabel", resourceCulture);
            }
        }
        
        public static string SettingsNumberOfSearchResultImagesToPreloadLabel {
            get {
                return ResourceManager.GetString("SettingsNumberOfSearchResultImagesToPreloadLabel", resourceCulture);
            }
        }
        
        public static string SettingsNumberOfLoadedImagesToKeepInMemoryLabel {
            get {
                return ResourceManager.GetString("SettingsNumberOfLoadedImagesToKeepInMemoryLabel", resourceCulture);
            }
        }
        
        public static string SettingsLocationLinkToolTip {
            get {
                return ResourceManager.GetString("SettingsLocationLinkToolTip", resourceCulture);
            }
        }
        
        public static string SettingsOverlayTextSizeToolTip {
            get {
                return ResourceManager.GetString("SettingsOverlayTextSizeToolTip", resourceCulture);
            }
        }
        
        public static string SettingsOverlayTextSizeForLargeModeToolTip {
            get {
                return ResourceManager.GetString("SettingsOverlayTextSizeForLargeModeToolTip", resourceCulture);
            }
        }
        
        public static string SettingsShortItemNameMaxLengthToolTip {
            get {
                return ResourceManager.GetString("SettingsShortItemNameMaxLengthToolTip", resourceCulture);
            }
        }
        
        public static string SettingsBlacklistedFilePathPatternsToolTip {
            get {
                return ResourceManager.GetString("SettingsBlacklistedFilePathPatternsToolTip", resourceCulture);
            }
        }
        
        public static string SettingsWhitelistedFilePathPatternsToolTip {
            get {
                return ResourceManager.GetString("SettingsWhitelistedFilePathPatternsToolTip", resourceCulture);
            }
        }
        
        public static string SettingsNumberOfSearchResultImagesToPreloadToolTip {
            get {
                return ResourceManager.GetString("SettingsNumberOfSearchResultImagesToPreloadToolTip", resourceCulture);
            }
        }
        
        public static string SettingsNumberOfLoadedImagesToKeepInMemoryToolTip {
            get {
                return ResourceManager.GetString("SettingsNumberOfLoadedImagesToKeepInMemoryToolTip", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseBackupTitle {
            get {
                return ResourceManager.GetString("ToolsDatabaseBackupTitle", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseExportTitle {
            get {
                return ResourceManager.GetString("ToolsDatabaseExportTitle", resourceCulture);
            }
        }
        
        public static string ToolsFilesCollectionFilteringTitle {
            get {
                return ResourceManager.GetString("ToolsFilesCollectionFilteringTitle", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseDataValidationTitle {
            get {
                return ResourceManager.GetString("ToolsDatabaseDataValidationTitle", resourceCulture);
            }
        }
        
        public static string ToolsFindMetaDataForMissingFilesTitle {
            get {
                return ResourceManager.GetString("ToolsFindMetaDataForMissingFilesTitle", resourceCulture);
            }
        }
        
        public static string ToolsRunButton {
            get {
                return ResourceManager.GetString("ToolsRunButton", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseBackupWarning1 {
            get {
                return ResourceManager.GetString("ToolsDatabaseBackupWarning1", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseExportInfo {
            get {
                return ResourceManager.GetString("ToolsDatabaseExportInfo", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseExportDirectoryLabel {
            get {
                return ResourceManager.GetString("ToolsDatabaseExportDirectoryLabel", resourceCulture);
            }
        }
        
        public static string ToolsFilesCollectionFilteringInfo {
            get {
                return ResourceManager.GetString("ToolsFilesCollectionFilteringInfo", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseDataValidationInfo {
            get {
                return ResourceManager.GetString("ToolsDatabaseDataValidationInfo", resourceCulture);
            }
        }
        
        public static string ToolsFindMetaDataForMissingFilesInfo {
            get {
                return ResourceManager.GetString("ToolsFindMetaDataForMissingFilesInfo", resourceCulture);
            }
        }
        
        public static string ToolsFindMetaDataForMissingFilesWarning {
            get {
                return ResourceManager.GetString("ToolsFindMetaDataForMissingFilesWarning", resourceCulture);
            }
        }
        
        public static string ToolsFindMetaDataForMissingFilesCopyButton {
            get {
                return ResourceManager.GetString("ToolsFindMetaDataForMissingFilesCopyButton", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseDataValidationCopyButton {
            get {
                return ResourceManager.GetString("ToolsDatabaseDataValidationCopyButton", resourceCulture);
            }
        }
        
        public static string ToolsFilesCollectionFilteringCopyButton {
            get {
                return ResourceManager.GetString("ToolsFilesCollectionFilteringCopyButton", resourceCulture);
            }
        }
        
        public static string FilesAddMetaDataTitle {
            get {
                return ResourceManager.GetString("FilesAddMetaDataTitle", resourceCulture);
            }
        }
        
        public static string FilesRemoveMetaDataTitle {
            get {
                return ResourceManager.GetString("FilesRemoveMetaDataTitle", resourceCulture);
            }
        }
        
        public static string FilesFindButton {
            get {
                return ResourceManager.GetString("FilesFindButton", resourceCulture);
            }
        }
        
        public static string FilesBrowseButton {
            get {
                return ResourceManager.GetString("FilesBrowseButton", resourceCulture);
            }
        }
        
        public static string FilesSelectAllButton {
            get {
                return ResourceManager.GetString("FilesSelectAllButton", resourceCulture);
            }
        }
        
        public static string FilesDeselectAllButton {
            get {
                return ResourceManager.GetString("FilesDeselectAllButton", resourceCulture);
            }
        }
        
        public static string FilesAddMetaDataForSelectedFilesButton {
            get {
                return ResourceManager.GetString("FilesAddMetaDataForSelectedFilesButton", resourceCulture);
            }
        }
        
        public static string FilesCopyFileListForAddedFilesButton {
            get {
                return ResourceManager.GetString("FilesCopyFileListForAddedFilesButton", resourceCulture);
            }
        }
        
        public static string FilesRemoveButton {
            get {
                return ResourceManager.GetString("FilesRemoveButton", resourceCulture);
            }
        }
        
        public static string FilesInfoText {
            get {
                return ResourceManager.GetString("FilesInfoText", resourceCulture);
            }
        }
        
        public static string FilesWarningText {
            get {
                return ResourceManager.GetString("FilesWarningText", resourceCulture);
            }
        }
        
        public static string FilesFromFilesCollectionLabel {
            get {
                return ResourceManager.GetString("FilesFromFilesCollectionLabel", resourceCulture);
            }
        }
        
        public static string FilesFromFilesCollectionSubDirectoryLabel {
            get {
                return ResourceManager.GetString("FilesFromFilesCollectionSubDirectoryLabel", resourceCulture);
            }
        }
        
        public static string FilesIncludeMetaDataToolTip {
            get {
                return ResourceManager.GetString("FilesIncludeMetaDataToolTip", resourceCulture);
            }
        }
        
        public static string FilesFileListLabel {
            get {
                return ResourceManager.GetString("FilesFileListLabel", resourceCulture);
            }
        }
        
        public static string FilesFileDateModifiedToolTip {
            get {
                return ResourceManager.GetString("FilesFileDateModifiedToolTip", resourceCulture);
            }
        }
        
        public static string FilesIncludeMetaDataLabel {
            get {
                return ResourceManager.GetString("FilesIncludeMetaDataLabel", resourceCulture);
            }
        }
        
        public static string BackupNotifierNoDatabaseBackupHasBeenCreated {
            get {
                return ResourceManager.GetString("BackupNotifierNoDatabaseBackupHasBeenCreated", resourceCulture);
            }
        }
        
        public static string BackupNotifierLongTimeSinceBackup {
            get {
                return ResourceManager.GetString("BackupNotifierLongTimeSinceBackup", resourceCulture);
            }
        }
        
        public static string BirthdayNotifierTodayIsTheBirthdayFor {
            get {
                return ResourceManager.GetString("BirthdayNotifierTodayIsTheBirthdayFor", resourceCulture);
            }
        }
        
        public static string BirthdayNotifierHappyBirthday {
            get {
                return ResourceManager.GetString("BirthdayNotifierHappyBirthday", resourceCulture);
            }
        }
        
        public static string RestInPeaceNotifierRestInPeace {
            get {
                return ResourceManager.GetString("RestInPeaceNotifierRestInPeace", resourceCulture);
            }
        }
        
        public static string StartupNotificationDemoConfigurationEnabled {
            get {
                return ResourceManager.GetString("StartupNotificationDemoConfigurationEnabled", resourceCulture);
            }
        }
        
        public static string CategorizationUpdateHistoryTitle {
            get {
                return ResourceManager.GetString("CategorizationUpdateHistoryTitle", resourceCulture);
            }
        }
        
        public static string CategorizationNoChanges {
            get {
                return ResourceManager.GetString("CategorizationNoChanges", resourceCulture);
            }
        }
        
        public static string CategorizationRemoveItemFromUpdateHistory {
            get {
                return ResourceManager.GetString("CategorizationRemoveItemFromUpdateHistory", resourceCulture);
            }
        }
        
        public static string CategorizationUpdateTitle {
            get {
                return ResourceManager.GetString("CategorizationUpdateTitle", resourceCulture);
            }
        }
        
        public static string CategorizationAddSelectedPersonToFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationAddSelectedPersonToFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationAddSelectedLocationToFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationAddSelectedLocationToFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationAddSelectedTagToFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationAddSelectedTagToFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationRemoveSelectedPersonFromFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationRemoveSelectedPersonFromFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationRemoveSelectedLocationFromFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationRemoveSelectedLocationFromFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationRemoveSelectedTagFromFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationRemoveSelectedTagFromFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationNewButton {
            get {
                return ResourceManager.GetString("CategorizationNewButton", resourceCulture);
            }
        }
        
        public static string CategorizationCreateANewPersonAndAddItToCurrentFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationCreateANewPersonAndAddItToCurrentFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationCreateANewLocationAndAddItToCurrentFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationCreateANewLocationAndAddItToCurrentFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationCreateANewTagAndAddItToCurrentFileToolTip {
            get {
                return ResourceManager.GetString("CategorizationCreateANewTagAndAddItToCurrentFileToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationSetButton {
            get {
                return ResourceManager.GetString("CategorizationSetButton", resourceCulture);
            }
        }
        
        public static string CategorizationSetFileDescriptionToolTip {
            get {
                return ResourceManager.GetString("CategorizationSetFileDescriptionToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationFileDescriptionToolTip {
            get {
                return ResourceManager.GetString("CategorizationFileDescriptionToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationFileDateAndTimeToolTip {
            get {
                return ResourceManager.GetString("CategorizationFileDateAndTimeToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationDateAndTimeFormatToolTip {
            get {
                return ResourceManager.GetString("CategorizationDateAndTimeFormatToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationSetFileDateAndTimeToolTip {
            get {
                return ResourceManager.GetString("CategorizationSetFileDateAndTimeToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationApplyMetaDataFromLastEditButton {
            get {
                return ResourceManager.GetString("CategorizationApplyMetaDataFromLastEditButton", resourceCulture);
            }
        }
        
        public static string CategorizationApplyMetaDataFromLastEditToolTip {
            get {
                return ResourceManager.GetString("CategorizationApplyMetaDataFromLastEditToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationReloadMetaDataButton {
            get {
                return ResourceManager.GetString("CategorizationReloadMetaDataButton", resourceCulture);
            }
        }
        
        public static string CategorizationReloadFileDateTimeGPSPositionAndOrientationToolTip {
            get {
                return ResourceManager.GetString("CategorizationReloadFileDateTimeGPSPositionAndOrientationToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationRotate90DegreesClockwiseToolTip {
            get {
                return ResourceManager.GetString("CategorizationRotate90DegreesClockwiseToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationRotate90DegreesCounterClockwiseToolTip {
            get {
                return ResourceManager.GetString("CategorizationRotate90DegreesCounterClockwiseToolTip", resourceCulture);
            }
        }
        
        public static string CategorizationReloadOrientationToolTip {
            get {
                return ResourceManager.GetString("CategorizationReloadOrientationToolTip", resourceCulture);
            }
        }
        
        public static string FileTypePicture {
            get {
                return ResourceManager.GetString("FileTypePicture", resourceCulture);
            }
        }
        
        public static string FileTypeMovie {
            get {
                return ResourceManager.GetString("FileTypeMovie", resourceCulture);
            }
        }
        
        public static string FileTypeDocument {
            get {
                return ResourceManager.GetString("FileTypeDocument", resourceCulture);
            }
        }
        
        public static string FileTypeAudio {
            get {
                return ResourceManager.GetString("FileTypeAudio", resourceCulture);
            }
        }
        
        public static string SexNotKnown {
            get {
                return ResourceManager.GetString("SexNotKnown", resourceCulture);
            }
        }
        
        public static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        public static string SexFemale {
            get {
                return ResourceManager.GetString("SexFemale", resourceCulture);
            }
        }
        
        public static string SexNotApplicable {
            get {
                return ResourceManager.GetString("SexNotApplicable", resourceCulture);
            }
        }
        
        public static string SortMethodDate {
            get {
                return ResourceManager.GetString("SortMethodDate", resourceCulture);
            }
        }
        
        public static string SortMethodDateDesc {
            get {
                return ResourceManager.GetString("SortMethodDateDesc", resourceCulture);
            }
        }
        
        public static string SortMethodPath {
            get {
                return ResourceManager.GetString("SortMethodPath", resourceCulture);
            }
        }
        
        public static string SortMethodPathDesc {
            get {
                return ResourceManager.GetString("SortMethodPathDesc", resourceCulture);
            }
        }
        
        public static string WindowModeNormal {
            get {
                return ResourceManager.GetString("WindowModeNormal", resourceCulture);
            }
        }
        
        public static string WindowModeMaximized {
            get {
                return ResourceManager.GetString("WindowModeMaximized", resourceCulture);
            }
        }
        
        public static string WindowModeFullscreen {
            get {
                return ResourceManager.GetString("WindowModeFullscreen", resourceCulture);
            }
        }
        
        public static string CategorizationMarkButton {
            get {
                return ResourceManager.GetString("CategorizationMarkButton", resourceCulture);
            }
        }
        
        public static string CategorizationMarkButtonToolTip {
            get {
                return ResourceManager.GetString("CategorizationMarkButtonToolTip", resourceCulture);
            }
        }
        
        public static string ToolsCreateDatabaseTitle {
            get {
                return ResourceManager.GetString("ToolsCreateDatabaseTitle", resourceCulture);
            }
        }
        
        public static string ToolsCreateDatabaseFileAlreadyExists {
            get {
                return ResourceManager.GetString("ToolsCreateDatabaseFileAlreadyExists", resourceCulture);
            }
        }
        
        public static string ToolsCreateDatabaseCreateDatabase {
            get {
                return ResourceManager.GetString("ToolsCreateDatabaseCreateDatabase", resourceCulture);
            }
        }
        
        public static string ToolsCreateDatabaseCreated {
            get {
                return ResourceManager.GetString("ToolsCreateDatabaseCreated", resourceCulture);
            }
        }
        
        public static string ToolsCreateBackupResult {
            get {
                return ResourceManager.GetString("ToolsCreateBackupResult", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseBackupFilesLabel {
            get {
                return ResourceManager.GetString("ToolsDatabaseBackupFilesLabel", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseBackupNoFilesFound {
            get {
                return ResourceManager.GetString("ToolsDatabaseBackupNoFilesFound", resourceCulture);
            }
        }
        
        public static string ToolsBackupDatabaseDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ToolsBackupDatabaseDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        public static string ToolsFoundNotApplicableFilesCountFilesThatNowShouldBeFiltered {
            get {
                return ResourceManager.GetString("ToolsFoundNotApplicableFilesCountFilesThatNowShouldBeFiltered", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseValidationFileError {
            get {
                return ResourceManager.GetString("ToolsDatabaseValidationFileError", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseValidationPersonError {
            get {
                return ResourceManager.GetString("ToolsDatabaseValidationPersonError", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseValidationLocationError {
            get {
                return ResourceManager.GetString("ToolsDatabaseValidationLocationError", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseValidationTagError {
            get {
                return ResourceManager.GetString("ToolsDatabaseValidationTagError", resourceCulture);
            }
        }
        
        public static string ToolsDabaseValidationErrorsFound {
            get {
                return ResourceManager.GetString("ToolsDabaseValidationErrorsFound", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseValidationNoErrorsFound {
            get {
                return ResourceManager.GetString("ToolsDatabaseValidationNoErrorsFound", resourceCulture);
            }
        }
        
        public static string ToolsFileListCopiedToClipboard {
            get {
                return ResourceManager.GetString("ToolsFileListCopiedToClipboard", resourceCulture);
            }
        }
        
        public static string ToolsNoMissingFilesFound {
            get {
                return ResourceManager.GetString("ToolsNoMissingFilesFound", resourceCulture);
            }
        }
        
        public static string ToolsMissingFilesFound {
            get {
                return ResourceManager.GetString("ToolsMissingFilesFound", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseExportNoSuchDirectory {
            get {
                return ResourceManager.GetString("ToolsDatabaseExportNoSuchDirectory", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseExportSpecifiedDirectoryIsNotEmpty {
            get {
                return ResourceManager.GetString("ToolsDatabaseExportSpecifiedDirectoryIsNotEmpty", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseExportResult {
            get {
                return ResourceManager.GetString("ToolsDatabaseExportResult", resourceCulture);
            }
        }
        
        public static string SettingsUnsavedSettingsNotification {
            get {
                return ResourceManager.GetString("SettingsUnsavedSettingsNotification", resourceCulture);
            }
        }
        
        public static string ToolsCreateDatabaseDescription {
            get {
                return ResourceManager.GetString("ToolsCreateDatabaseDescription", resourceCulture);
            }
        }
        
        public static string NotificationDatabaseIsMissing {
            get {
                return ResourceManager.GetString("NotificationDatabaseIsMissing", resourceCulture);
            }
        }
        
        public static string ToolsDatabaseExportDestinationDirectoryBrowseButton {
            get {
                return ResourceManager.GetString("ToolsDatabaseExportDestinationDirectoryBrowseButton", resourceCulture);
            }
        }
        
        public static string ExportSearchResultPdfLabel {
            get {
                return ResourceManager.GetString("ExportSearchResultPdfLabel", resourceCulture);
            }
        }
        
        public static string ExportDataLabel {
            get {
                return ResourceManager.GetString("ExportDataLabel", resourceCulture);
            }
        }
        
        public static string AboutAppVersion {
            get {
                return ResourceManager.GetString("AboutAppVersion", resourceCulture);
            }
        }
        
        public static string AboutAppAuthor {
            get {
                return ResourceManager.GetString("AboutAppAuthor", resourceCulture);
            }
        }
        
        public static string AboutAppProjectWebsite {
            get {
                return ResourceManager.GetString("AboutAppProjectWebsite", resourceCulture);
            }
        }
        
        public static string ExportSelectYourDestinationDirectory {
            get {
                return ResourceManager.GetString("ExportSelectYourDestinationDirectory", resourceCulture);
            }
        }
        
        public static string ExportDestinationDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ExportDestinationDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        public static string ExportDestinationDirectoryIsNotEmpty {
            get {
                return ResourceManager.GetString("ExportDestinationDirectoryIsNotEmpty", resourceCulture);
            }
        }
        
        public static string ExportNothingToExport {
            get {
                return ResourceManager.GetString("ExportNothingToExport", resourceCulture);
            }
        }
        
        public static string ExportSelectedData {
            get {
                return ResourceManager.GetString("ExportSelectedData", resourceCulture);
            }
        }
        
        public static string ExportExporting {
            get {
                return ResourceManager.GetString("ExportExporting", resourceCulture);
            }
        }
        
        public static string ExportFinishedSuccessfully {
            get {
                return ResourceManager.GetString("ExportFinishedSuccessfully", resourceCulture);
            }
        }
        
        public static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        public static string FilterTypeNoMetaData {
            get {
                return ResourceManager.GetString("FilterTypeNoMetaData", resourceCulture);
            }
        }
        
        public static string FilterTypeNoDateTime {
            get {
                return ResourceManager.GetString("FilterTypeNoDateTime", resourceCulture);
            }
        }
        
        public static string FilterTypeText {
            get {
                return ResourceManager.GetString("FilterTypeText", resourceCulture);
            }
        }
        
        public static string FilterTypeFileList {
            get {
                return ResourceManager.GetString("FilterTypeFileList", resourceCulture);
            }
        }
        
        public static string FilterTypeFileType {
            get {
                return ResourceManager.GetString("FilterTypeFileType", resourceCulture);
            }
        }
        
        public static string FilterTypePerson {
            get {
                return ResourceManager.GetString("FilterTypePerson", resourceCulture);
            }
        }
        
        public static string FilterTypeLocation {
            get {
                return ResourceManager.GetString("FilterTypeLocation", resourceCulture);
            }
        }
        
        public static string FilterTypeTag {
            get {
                return ResourceManager.GetString("FilterTypeTag", resourceCulture);
            }
        }
        
        public static string FilterTypePersonAge {
            get {
                return ResourceManager.GetString("FilterTypePersonAge", resourceCulture);
            }
        }
        
        public static string FilterTypePersonSex {
            get {
                return ResourceManager.GetString("FilterTypePersonSex", resourceCulture);
            }
        }
        
        public static string FilterTypeDateTime {
            get {
                return ResourceManager.GetString("FilterTypeDateTime", resourceCulture);
            }
        }
        
        public static string FilterTypePosition {
            get {
                return ResourceManager.GetString("FilterTypePosition", resourceCulture);
            }
        }
        
        public static string FilterTypeNumPersons {
            get {
                return ResourceManager.GetString("FilterTypeNumPersons", resourceCulture);
            }
        }
        
        public static string SearchFiltersLabel {
            get {
                return ResourceManager.GetString("SearchFiltersLabel", resourceCulture);
            }
        }
        
        public static string SearchFilterDateTimeStart {
            get {
                return ResourceManager.GetString("SearchFilterDateTimeStart", resourceCulture);
            }
        }
        
        public static string SearchFilterDateTimeEnd {
            get {
                return ResourceManager.GetString("SearchFilterDateTimeEnd", resourceCulture);
            }
        }
        
        public static string SearchFilterFileListToolTip {
            get {
                return ResourceManager.GetString("SearchFilterFileListToolTip", resourceCulture);
            }
        }
        
        public static string SearchFilterNumPersonsMin {
            get {
                return ResourceManager.GetString("SearchFilterNumPersonsMin", resourceCulture);
            }
        }
        
        public static string SearchFilterNumPersonsMax {
            get {
                return ResourceManager.GetString("SearchFilterNumPersonsMax", resourceCulture);
            }
        }
        
        public static string SearchFilterPersonAgeFrom {
            get {
                return ResourceManager.GetString("SearchFilterPersonAgeFrom", resourceCulture);
            }
        }
        
        public static string SearchFilterPersonAgeTo {
            get {
                return ResourceManager.GetString("SearchFilterPersonAgeTo", resourceCulture);
            }
        }
        
        public static string SearchFilterPersonSexTooltip {
            get {
                return ResourceManager.GetString("SearchFilterPersonSexTooltip", resourceCulture);
            }
        }
        
        public static string SearchFilterPositionInputToolTip {
            get {
                return ResourceManager.GetString("SearchFilterPositionInputToolTip", resourceCulture);
            }
        }
        
        public static string SearchFilterPositionRadiusInputToolTip {
            get {
                return ResourceManager.GetString("SearchFilterPositionRadiusInputToolTip", resourceCulture);
            }
        }
        
        public static string SearchFilterTextInputToolTip {
            get {
                return ResourceManager.GetString("SearchFilterTextInputToolTip", resourceCulture);
            }
        }
        
        public static string AddPersonDateOfBirthToolTip {
            get {
                return ResourceManager.GetString("AddPersonDateOfBirthToolTip", resourceCulture);
            }
        }
        
        public static string AddPersonDeceasedToolTip {
            get {
                return ResourceManager.GetString("AddPersonDeceasedToolTip", resourceCulture);
            }
        }
        
        public static string SearchToggleText {
            get {
                return ResourceManager.GetString("SearchToggleText", resourceCulture);
            }
        }
        
        public static string SearchImageLoadingError {
            get {
                return ResourceManager.GetString("SearchImageLoadingError", resourceCulture);
            }
        }
        
        public static string SearchFileTypeNotSupported {
            get {
                return ResourceManager.GetString("SearchFileTypeNotSupported", resourceCulture);
            }
        }
        
        public static string SearchNoMatch {
            get {
                return ResourceManager.GetString("SearchNoMatch", resourceCulture);
            }
        }
        
        public static string SearchFileDateTimeThisYear {
            get {
                return ResourceManager.GetString("SearchFileDateTimeThisYear", resourceCulture);
            }
        }
        
        public static string SearchFileDateTimeYearAgo {
            get {
                return ResourceManager.GetString("SearchFileDateTimeYearAgo", resourceCulture);
            }
        }
        
        public static string SearchFileDateTimeYearsAgo {
            get {
                return ResourceManager.GetString("SearchFileDateTimeYearsAgo", resourceCulture);
            }
        }
        
        public static string NotificationDatabaseMigration {
            get {
                return ResourceManager.GetString("NotificationDatabaseMigration", resourceCulture);
            }
        }
        
        public static string NotificationDatabaseMigrationError {
            get {
                return ResourceManager.GetString("NotificationDatabaseMigrationError", resourceCulture);
            }
        }
        
        public static string FileTypeUnknown {
            get {
                return ResourceManager.GetString("FileTypeUnknown", resourceCulture);
            }
        }
        
        public static string SettingsThemeLabel {
            get {
                return ResourceManager.GetString("SettingsThemeLabel", resourceCulture);
            }
        }
        
        public static string AboutCommandLineArgPath {
            get {
                return ResourceManager.GetString("AboutCommandLineArgPath", resourceCulture);
            }
        }
        
        public static string TextFilterCaseSensitive {
            get {
                return ResourceManager.GetString("TextFilterCaseSensitive", resourceCulture);
            }
        }
        
        public static string SearchCombineSearchCurrent {
            get {
                return ResourceManager.GetString("SearchCombineSearchCurrent", resourceCulture);
            }
        }
        
        public static string SearchCombineSearchCurrentToolTip {
            get {
                return ResourceManager.GetString("SearchCombineSearchCurrentToolTip", resourceCulture);
            }
        }
        
        public static string FilterNegateTooltip {
            get {
                return ResourceManager.GetString("FilterNegateTooltip", resourceCulture);
            }
        }
        
        public static string FilterTypeSeason {
            get {
                return ResourceManager.GetString("FilterTypeSeason", resourceCulture);
            }
        }
        
        public static string SeasonSpring {
            get {
                return ResourceManager.GetString("SeasonSpring", resourceCulture);
            }
        }
        
        public static string SeasonSummer {
            get {
                return ResourceManager.GetString("SeasonSummer", resourceCulture);
            }
        }
        
        public static string SeasonAutumn {
            get {
                return ResourceManager.GetString("SeasonAutumn", resourceCulture);
            }
        }
        
        public static string SeasonWinter {
            get {
                return ResourceManager.GetString("SeasonWinter", resourceCulture);
            }
        }
        
        public static string FilterTypeAnnualDate {
            get {
                return ResourceManager.GetString("FilterTypeAnnualDate", resourceCulture);
            }
        }
        
        public static string SearchFilterRange {
            get {
                return ResourceManager.GetString("SearchFilterRange", resourceCulture);
            }
        }
        
        public static string FilterTypeTime {
            get {
                return ResourceManager.GetString("FilterTypeTime", resourceCulture);
            }
        }
        
        public static string TextFilterIncludeTags {
            get {
                return ResourceManager.GetString("TextFilterIncludeTags", resourceCulture);
            }
        }
        
        public static string TextFilterIncludePersons {
            get {
                return ResourceManager.GetString("TextFilterIncludePersons", resourceCulture);
            }
        }
        
        public static string TextFilterIncludeLocations {
            get {
                return ResourceManager.GetString("TextFilterIncludeLocations", resourceCulture);
            }
        }
        
        public static string AboutGettingStarted3 {
            get {
                return ResourceManager.GetString("AboutGettingStarted3", resourceCulture);
            }
        }
        
        public static string ThemeDefault {
            get {
                return ResourceManager.GetString("ThemeDefault", resourceCulture);
            }
        }
        
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        public static string AddPersonClearCurrentFileToolTip {
            get {
                return ResourceManager.GetString("AddPersonClearCurrentFileToolTip", resourceCulture);
            }
        }
        
        public static string AddPersonCopyCurrentFileToolTip {
            get {
                return ResourceManager.GetString("AddPersonCopyCurrentFileToolTip", resourceCulture);
            }
        }
        
        public static string BirthdaysSearch {
            get {
                return ResourceManager.GetString("BirthdaysSearch", resourceCulture);
            }
        }
        
        public static string BirthdaysAddPersonSearchFilter {
            get {
                return ResourceManager.GetString("BirthdaysAddPersonSearchFilter", resourceCulture);
            }
        }
        
        public static string BirthdaysSearchForDate {
            get {
                return ResourceManager.GetString("BirthdaysSearchForDate", resourceCulture);
            }
        }
        
        public static string BirthdaysAddDateSearchFilter {
            get {
                return ResourceManager.GetString("BirthdaysAddDateSearchFilter", resourceCulture);
            }
        }
        
        public static string FileInfoSearchLocation {
            get {
                return ResourceManager.GetString("FileInfoSearchLocation", resourceCulture);
            }
        }
        
        public static string FileInfoAddLocationSearchFilter {
            get {
                return ResourceManager.GetString("FileInfoAddLocationSearchFilter", resourceCulture);
            }
        }
        
        public static string FileInfoSearchTag {
            get {
                return ResourceManager.GetString("FileInfoSearchTag", resourceCulture);
            }
        }
        
        public static string FileInfoAddTagSearchFilter {
            get {
                return ResourceManager.GetString("FileInfoAddTagSearchFilter", resourceCulture);
            }
        }
        
        public static string FilterTypeAllFiles {
            get {
                return ResourceManager.GetString("FilterTypeAllFiles", resourceCulture);
            }
        }
    }
}
