//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileDB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileDB.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seach files between dates.
        /// </summary>
        public static string SeachFilesBetweenDatesToolTip {
            get {
                return ResourceManager.GetString("SeachFilesBetweenDatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seach files by type.
        /// </summary>
        public static string SeachFilesByTypeToolTip {
            get {
                return ResourceManager.GetString("SeachFilesByTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seach files in specified area.
        /// </summary>
        public static string SeachFilesInSpecifiedAreaToolTip {
            get {
                return ResourceManager.GetString("SeachFilesInSpecifiedAreaToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string SearchAdvancedLabel {
            get {
                return ResourceManager.GetString("SearchAdvancedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string SearchAllFilesButton {
            get {
                return ResourceManager.GetString("SearchAllFilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all files except what was specified.
        /// </summary>
        public static string SearchAllFilesExceptWhatWasSpecifiedToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesExceptWhatWasSpecifiedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files from search 1 and 2.
        /// </summary>
        public static string SearchAllFilesFromSearch1And2ToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesFromSearch1And2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files from search 1 that also belong to search 2.
        /// </summary>
        public static string SearchAllFilesFromSearch1ThatAlsoBelongToSearch2ToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesFromSearch1ThatAlsoBelongToSearch2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files that are in either of the searches, but not in their intersection.
        /// </summary>
        public static string SearchAllFilesThatAreInEitherOfTheSearchesButNotInTheirIntersectionToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesThatAreInEitherOfTheSearchesButNotInTheirIntersectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all files.
        /// </summary>
        public static string SearchAllFilesToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search all files within current file directory (recursive).
        /// </summary>
        public static string SearchAllFilesWithinCurrentFileDirectoryToolTip {
            get {
                return ResourceManager.GetString("SearchAllFilesWithinCurrentFileDirectoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All from current directory.
        /// </summary>
        public static string SearchAllFromCurrentDirectoryButton {
            get {
                return ResourceManager.GetString("SearchAllFromCurrentDirectoryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All without meta-data.
        /// </summary>
        public static string SearchAllWithoutMetaDataButton {
            get {
                return ResourceManager.GetString("SearchAllWithoutMetaDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string SearchAnyButton {
            get {
                return ResourceManager.GetString("SearchAnyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string SearchBasicLabel {
            get {
                return ResourceManager.GetString("SearchBasicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string SearchBrowseButton {
            get {
                return ResourceManager.GetString("SearchBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by file list.
        /// </summary>
        public static string SearchByFileListToolTip {
            get {
                return ResourceManager.GetString("SearchByFileListToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by location.
        /// </summary>
        public static string SearchByLocationToolTip {
            get {
                return ResourceManager.GetString("SearchByLocationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by only selected persons.
        /// </summary>
        public static string SearchByOnlySelectedPersonsToolTip {
            get {
                return ResourceManager.GetString("SearchByOnlySelectedPersonsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by only selected person.
        /// </summary>
        public static string SearchByOnlySelectedPersonToolTip {
            get {
                return ResourceManager.GetString("SearchByOnlySelectedPersonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by selected person and others.
        /// </summary>
        public static string SearchBySelectedPersonAndOthersToolTip {
            get {
                return ResourceManager.GetString("SearchBySelectedPersonAndOthersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by selected persons and others.
        /// </summary>
        public static string SearchBySelectedPersonsAndOthersToolTip {
            get {
                return ResourceManager.GetString("SearchBySelectedPersonsAndOthersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by selected persons.
        /// </summary>
        public static string SearchBySelectedPersonsToolTip {
            get {
                return ResourceManager.GetString("SearchBySelectedPersonsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by selected person.
        /// </summary>
        public static string SearchBySelectedPersonToolTip {
            get {
                return ResourceManager.GetString("SearchBySelectedPersonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by sex (ISO/IEC 5218).
        /// </summary>
        public static string SearchBySexToolTip {
            get {
                return ResourceManager.GetString("SearchBySexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by tag.
        /// </summary>
        public static string SearchByTagToolTip {
            get {
                return ResourceManager.GetString("SearchByTagToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string SearchCategoriesLabel {
            get {
                return ResourceManager.GetString("SearchCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine.
        /// </summary>
        public static string SearchCombineLabel {
            get {
                return ResourceManager.GetString("SearchCombineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string SearchCombineResultLabel {
            get {
                return ResourceManager.GetString("SearchCombineResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search 1:.
        /// </summary>
        public static string SearchCombineSearch1Label {
            get {
                return ResourceManager.GetString("SearchCombineSearch1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search 2:.
        /// </summary>
        public static string SearchCombineSearch2Label {
            get {
                return ResourceManager.GetString("SearchCombineSearch2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        public static string SearchComplementButton {
            get {
                return ResourceManager.GetString("SearchComplementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string SearchCopyButton {
            get {
                return ResourceManager.GetString("SearchCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string SearchDifferenceButton {
            get {
                return ResourceManager.GetString("SearchDifferenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File date:.
        /// </summary>
        public static string SearchFileDateLabel {
            get {
                return ResourceManager.GetString("SearchFileDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list:.
        /// </summary>
        public static string SearchFileListLabel {
            get {
                return ResourceManager.GetString("SearchFileListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type:.
        /// </summary>
        public static string SearchFileTypeLabel {
            get {
                return ResourceManager.GetString("SearchFileTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for files within selected directory.
        /// </summary>
        public static string SearchForFilesWithinSelectedDirectoryToolTip {
            get {
                return ResourceManager.GetString("SearchForFilesWithinSelectedDirectoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for file with persons of the specified age.
        /// </summary>
        public static string SearchForFileWithPersonsOfTheSpecifiedAgeToolTip {
            get {
                return ResourceManager.GetString("SearchForFileWithPersonsOfTheSpecifiedAgeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: LAT LON.
        /// </summary>
        public static string SearchFormatLATLONToolTip {
            get {
                return ResourceManager.GetString("SearchFormatLATLONToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From age (years).
        /// </summary>
        public static string SearchFromAgeYearsToolTip {
            get {
                return ResourceManager.GetString("SearchFromAgeYearsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From current file.
        /// </summary>
        public static string SearchFromCurrentFileButton {
            get {
                return ResourceManager.GetString("SearchFromCurrentFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Maps URL:.
        /// </summary>
        public static string SearchGoogleMapsURLLabel {
            get {
                return ResourceManager.GetString("SearchGoogleMapsURLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string SearchGroupButton {
            get {
                return ResourceManager.GetString("SearchGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection.
        /// </summary>
        public static string SearchIntersectionButton {
            get {
                return ResourceManager.GetString("SearchIntersectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude longitude:.
        /// </summary>
        public static string SearchLatitudeLongitudeLabel {
            get {
                return ResourceManager.GetString("SearchLatitudeLongitudeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string SearchLocationsToolTip {
            get {
                return ResourceManager.GetString("SearchLocationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location (with GPS position):.
        /// </summary>
        public static string SearchLocationWithGPSPositionLabel {
            get {
                return ResourceManager.GetString("SearchLocationWithGPSPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New files.
        /// </summary>
        public static string SearchNewFilesButton {
            get {
                return ResourceManager.GetString("SearchNewFilesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for newly added files meta-data.
        /// </summary>
        public static string SearchNewFilesButtonToolTip {
            get {
                return ResourceManager.GetString("SearchNewFilesButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string SearchOpenButton {
            get {
                return ResourceManager.GetString("SearchOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person #1.
        /// </summary>
        public static string SearchPerson1ToolTip {
            get {
                return ResourceManager.GetString("SearchPerson1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person #2.
        /// </summary>
        public static string SearchPerson2ToolTip {
            get {
                return ResourceManager.GetString("SearchPerson2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person age:.
        /// </summary>
        public static string SearchPersonAgeLabel {
            get {
                return ResourceManager.GetString("SearchPersonAgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person sex:.
        /// </summary>
        public static string SearchPersonSexLabel {
            get {
                return ResourceManager.GetString("SearchPersonSexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string SearchPersonsToolTip {
            get {
                return ResourceManager.GetString("SearchPersonsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string SearchPositionLabel {
            get {
                return ResourceManager.GetString("SearchPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius in meters.
        /// </summary>
        public static string SearchRadiusInMetersToolTip {
            get {
                return ResourceManager.GetString("SearchRadiusInMetersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius [m]:.
        /// </summary>
        public static string SearchRadiusLabel {
            get {
                return ResourceManager.GetString("SearchRadiusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random files:.
        /// </summary>
        public static string SearchRandomFilesLabel {
            get {
                return ResourceManager.GetString("SearchRandomFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search random files.
        /// </summary>
        public static string SearchRandomFilesToolTip {
            get {
                return ResourceManager.GetString("SearchRandomFilesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string SearchTagsToolTip {
            get {
                return ResourceManager.GetString("SearchTagsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string SearchTextLabel {
            get {
                return ResourceManager.GetString("SearchTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search criteria for text (matches file path/description).
        /// </summary>
        public static string SearchTextToolTip {
            get {
                return ResourceManager.GetString("SearchTextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To age (years).
        /// </summary>
        public static string SearchToAgeYearsToolTip {
            get {
                return ResourceManager.GetString("SearchToAgeYearsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Union.
        /// </summary>
        public static string SearchUnionButton {
            get {
                return ResourceManager.GetString("SearchUnionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string SearchUniqueButton {
            get {
                return ResourceManager.GetString("SearchUniqueButton", resourceCulture);
            }
        }
    }
}
